// Researched seed catalogue. Products carry label/reference macros; recipes
// carry weighed components and have their macros calculated at load by
// resolveCatalog, so a component correction flows into every recipe using it.

import { resolveCatalog, type Food, type NutritionSource } from "./food-model";

export type { Food, FoodComponent, FoodImage, NutritionSource } from "./food-model";
/** @deprecated Retained for older imports; every food is a `Food` now. */
export type NutritionItem = Food;

export const SOURCE_LINKS = {
  ifct: "https://www.nin.res.in/ebooks/IFCT2017_16122024.pdf",
  ninGuidelines: "https://www.nin.res.in/dietaryguidelines/pdfjs/locale/DGI24thJune2024fin.pdf",
  usda: "https://fdc.nal.usda.gov/",
  fssai: "https://www.fssai.gov.in/upload/uploadfiles/files/Guidelines_Nutrition_Labelling_16_08_2018.pdf",
  openFoodFacts: "https://world.openfoodfacts.org/",
};

const usdaSource: NutritionSource = { label: "USDA FoodData Central", url: SOURCE_LINKS.usda, trust: "Reference" };

type ProductSeed = Omit<Food, "kind" | "brand" | "variant" | "category"> & {
  brand?: string;
  variant?: string;
  category?: Food["category"];
};

const productSeeds: ProductSeed[] = [
  {
    id: "nandini-goodlife-toned",
    name: "GoodLife UHT toned milk",
    brand: "Nandini",
    amount: 100,
    unit: "ml",
    calories: 60,
    protein: 3.3,
    carbs: 4.8,
    fat: 3.1,
    fiber: 0,
    category: "Ordered",
    packSize: "1 L carton",
    availability: "BigBasket · Bengaluru",
    common: true,
    aliases: ["milk", "toned milk", "good life", "kmf"],
    source: { label: "Current retailer label · KMF product", url: "https://www.bigbasket.com/pd/100285703/nandini-goodlife-toned-milk-1-l-carton/", trust: "Label mirror" },
  },
  {
    id: "epigamia-natural-greek",
    name: "Natural Greek yogurt",
    brand: "Epigamia",
    amount: 90,
    unit: "g",
    calories: 64,
    protein: 7,
    carbs: 3,
    fat: 2,
    fiber: 0,
    category: "Ordered",
    packSize: "90 g cup",
    availability: "Instamart-style quick commerce",
    common: true,
    aliases: ["greek yoghurt", "curd", "dahi", "epigamia"],
    source: { label: "Product-label mirror · recheck exact pack", url: "https://www.eatthismuch.com/calories/greek-yogurt-natural-1806163", trust: "Label mirror" },
  },
  {
    id: "muscleblaze-biozyme-whey",
    name: "Biozyme Whey · Rich Milk Chocolate",
    brand: "MuscleBlaze",
    amount: 1,
    unit: "scoop",
    calories: 131.68,
    protein: 25,
    carbs: 3.87,
    fat: 1.76,
    fiber: 0,
    category: "Ordered",
    packSize: "33 g scoop",
    availability: "Amazon India / brand store",
    common: true,
    aliases: ["whey", "protein powder", "biozyme", "shake"],
    source: { label: "MuscleBlaze official · 33 g scoop", url: "https://biozyme.muscleblaze.com/what-is-biozyme-whey.php", trust: "Official label" },
  },
  {
    id: "amul-high-protein-buttermilk",
    name: "High Protein Buttermilk",
    brand: "Amul",
    amount: 1,
    unit: "pack",
    calories: 108,
    protein: 15,
    carbs: 8,
    fat: 1,
    fiber: 0,
    category: "Product",
    packSize: "200 ml pack",
    availability: "Amul online · India",
    common: true,
    aliases: ["chaas", "buttermilk", "protein drink"],
    source: { label: "Amul official · 200 ml pack", url: "https://old.amul.com/products/amul-highprotein-buttermilk-info.php", trust: "Official label" },
  },
  {
    id: "amul-high-protein-paneer",
    name: "High Protein Paneer",
    brand: "Amul",
    amount: 100,
    unit: "g",
    calories: 170,
    protein: 25,
    carbs: 4,
    fat: 6,
    fiber: 0,
    category: "Product",
    packSize: "200 g tin",
    availability: "Amul online · India",
    common: true,
    aliases: ["low fat paneer", "cottage cheese", "amul paneer"],
    source: { label: "Amul official", url: "https://old.amul.com/products/amul-HP-tin-paneer-info.php", trust: "Official label" },
  },
  // Branded Indian staples KP reorders. Every one of these carries a real pack
  // label — a branded grocery almost always does, so "no label found" is a
  // reason to search harder, not to fall back to a generic reference food.
  {
    id: "fortune-poha-thick",
    name: "Poha · thick",
    brand: "Fortune",
    amount: 100,
    unit: "g",
    calories: 361.3,
    protein: 7.4,
    carbs: 77.2,
    fat: 1.6,
    fiber: 4.3,
    sugar: 0.5,
    sodium: 0.9,
    category: "Ordered",
    packSize: "500 g pouch · dry",
    barcode: "8906008812817",
    availability: "BigBasket / Instamart · Bengaluru",
    common: true,
    aliases: ["poha", "flattened rice", "avalakki", "chivda", "beaten rice"],
    images: [{ url: "/food-images/fortune-poha-thick.jpg", kind: "pack", credit: "Open Food Facts" }],
    source: { label: "Pack label · Open Food Facts 8906008812817", url: "https://world.openfoodfacts.org/product/8906008812817", trust: "Label mirror" },
  },
  {
    id: "bambino-vermicelli",
    name: "Long Cut Vermicelli",
    brand: "Bambino",
    amount: 100,
    unit: "g",
    calories: 347,
    protein: 10.5,
    carbs: 73.9,
    // Bambino's pack declares no dietary fibre, so none is claimed here.
    fiber: 0,
    fat: 1,
    sugar: 0.3,
    sodium: 9.7,
    category: "Ordered",
    packSize: "450 g pack · dry",
    availability: "BigBasket / Instamart · Bengaluru",
    common: true,
    aliases: ["vermicelli", "semiya", "sevai", "shavige", "upma"],
    source: { label: "Bambino official · fibre not declared on pack", url: "https://bambinopasta.in/products/bambino-long-cut-vermicelli", trust: "Official label" },
  },
  {
    id: "24-mantra-kabuli-chana",
    name: "Organic Kabuli Chana",
    brand: "24 Mantra Organic",
    amount: 100,
    unit: "g",
    calories: 342.9,
    protein: 22.9,
    carbs: 60,
    fat: 5.7,
    fiber: 14.3,
    sugar: 0,
    sodium: 0,
    category: "Ordered",
    packSize: "500 g pouch · dry",
    barcode: "8904083512219",
    availability: "BigBasket / Instamart · Bengaluru",
    common: true,
    aliases: ["chickpea", "kabuli chana", "chana", "garbanzo", "chole", "organic chickpea"],
    images: [{ url: "/food-images/24-mantra-kabuli-chana.jpg", kind: "pack", credit: "Open Food Facts" }],
    source: { label: "Pack label · Open Food Facts 8904083512219 · dry weight", url: "https://world.openfoodfacts.org/product/8904083512219", trust: "Label mirror" },
  },
  {
    id: "tata-sampann-toor-dal",
    name: "Unpolished Toor Dal",
    brand: "Tata Sampann",
    amount: 100,
    unit: "g",
    calories: 364,
    protein: 18.2,
    carbs: 64.3,
    fat: 1.3,
    fiber: 11.6,
    sugar: 0.5,
    sodium: 14.4,
    category: "Ordered",
    packSize: "1 kg pouch · dry",
    barcode: "8904043926216",
    availability: "BigBasket / Instamart · Bengaluru",
    common: true,
    aliases: ["toor dal", "arhar", "tur", "pigeon pea", "dal", "sambar"],
    images: [{ url: "/food-images/tata-sampann-toor-dal.jpg", kind: "pack", credit: "Open Food Facts" }],
    source: { label: "Pack label · Open Food Facts 8904043926216 · dry weight", url: "https://world.openfoodfacts.org/product/8904043926216", trust: "Label mirror" },
  },
  {
    // One nutrition label, eaten as a meal: stays a product, lists under Meals too.
    id: "mtr-poha-instant",
    name: "Instant Poha",
    brand: "MTR",
    amount: 1,
    unit: "pack",
    calories: 149,
    protein: 2.9,
    carbs: 24.2,
    fat: 4.3,
    fiber: 1.1,
    sugar: 1.6,
    sodium: 192,
    category: "Ordered",
    packSize: "60 g single-serve pouch",
    barcode: "8901042967325",
    preparedMeal: true,
    availability: "Instamart / Amazon · Bengaluru",
    aliases: ["instant poha", "ready to eat", "breakfast pouch", "mtr poha"],
    tags: ["Breakfast", "Ready to eat"],
    images: [{ url: "/food-images/mtr-poha-instant.jpg", kind: "pack", credit: "Open Food Facts" }],
    source: { label: "Pack label · Open Food Facts 8901042967325 · whole 60 g pouch", url: "https://world.openfoodfacts.org/product/8901042967325", trust: "Label mirror" },
  },
  { id: "banana", name: "Banana · medium", amount: 118, unit: "g", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, category: "Ingredient", availability: "Bengaluru staple", common: true, aliases: ["kela", "fruit"], source: usdaSource },
  { id: "chia", name: "Chia seeds", amount: 25, unit: "g", calories: 122, protein: 4.1, carbs: 10.5, fat: 7.7, fiber: 8.6, category: "Ingredient", availability: "BigBasket · Bengaluru", common: true, aliases: ["seeds", "omega 3", "pudding"], source: usdaSource },
  { id: "oats", name: "Rolled oats · dry", amount: 40, unit: "g", calories: 152, protein: 5.3, carbs: 27.1, fat: 2.6, fiber: 4, category: "Ingredient", availability: "Widely available in India", aliases: ["oatmeal", "porridge"], source: usdaSource },
  { id: "cauliflower", name: "Cauliflower · raw", amount: 250, unit: "g", calories: 63, protein: 4.8, carbs: 12.4, fat: 0.7, fiber: 5, category: "Ingredient", availability: "Bengaluru produce", aliases: ["gobi", "cauliflower rice", "vegetable"], source: usdaSource },
  { id: "chicken-breast", name: "Chicken breast · cooked", amount: 150, unit: "g", calories: 248, protein: 46.5, carbs: 0, fat: 5.4, fiber: 0, category: "Ingredient", availability: "Bengaluru poultry / quick commerce", aliases: ["boneless chicken", "roasted chicken"], source: usdaSource },
  { id: "rajma-cooked", name: "Rajma · cooked", amount: 150, unit: "g", calories: 191, protein: 13, carbs: 34.2, fat: 0.8, fiber: 9.6, category: "Ingredient", availability: "Bengaluru staple", aliases: ["kidney beans", "beans"], source: usdaSource },
  { id: "quinoa-cooked", name: "Quinoa · cooked", amount: 150, unit: "g", calories: 180, protein: 6.6, carbs: 31.9, fat: 2.9, fiber: 4.2, category: "Ingredient", availability: "BigBasket / supermarkets", aliases: ["grain", "seed"], source: usdaSource },
  { id: "spinach", name: "Spinach · raw", amount: 100, unit: "g", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, category: "Ingredient", availability: "Bengaluru produce", aliases: ["palak", "greens"], source: usdaSource },
  { id: "egg-whites", name: "Egg whites", amount: 100, unit: "g", calories: 52, protein: 10.9, carbs: 0.7, fat: 0.2, fiber: 0, category: "Ingredient", availability: "Bengaluru staple", aliases: ["eggs", "albumen"], source: usdaSource },
  { id: "cocoa", name: "Unsweetened cocoa powder", amount: 20, unit: "g", calories: 46, protein: 3.9, carbs: 11.6, fat: 2.7, fiber: 7.4, category: "Ingredient", availability: "Baking aisle / online India", aliases: ["cacao", "chocolate", "brownie"], source: usdaSource },
  { id: "chickpeas-cooked", name: "Chickpeas · cooked", amount: 100, unit: "g", calories: 164, protein: 8.9, carbs: 27.4, fat: 2.6, fiber: 7.6, category: "Ingredient", availability: "Bengaluru staple", aliases: ["chana", "kabuli chana", "garbanzo"], source: usdaSource },
  { id: "green-peas-cooked", name: "Green peas · cooked", amount: 100, unit: "g", calories: 84, protein: 5.4, carbs: 15.6, fat: 0.4, fiber: 5.5, category: "Ingredient", availability: "Bengaluru produce / frozen aisle", aliases: ["matar", "peas"], source: usdaSource },
  { id: "mango", name: "Mango · raw", amount: 150, unit: "g", calories: 90, protein: 1.2, carbs: 22.5, fat: 0.6, fiber: 2.4, category: "Ingredient", availability: "Seasonal Bengaluru produce", aliases: ["aam", "fruit"], source: usdaSource },
  { id: "strawberries", name: "Strawberries · raw", amount: 100, unit: "g", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, category: "Ingredient", availability: "Seasonal / frozen Bengaluru", aliases: ["berries", "fruit"], source: usdaSource },
  { id: "pomegranate", name: "Pomegranate arils", amount: 100, unit: "g", calories: 83, protein: 1.7, carbs: 18.7, fat: 1.2, fiber: 4, category: "Ingredient", availability: "Bengaluru produce", aliases: ["anar", "fruit"], source: usdaSource },
  { id: "cucumber", name: "Cucumber · raw", amount: 100, unit: "g", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, category: "Ingredient", availability: "Bengaluru produce", aliases: ["kheera", "salad", "kachumber"], source: usdaSource },
  { id: "tomato", name: "Tomato · raw", amount: 100, unit: "g", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, category: "Ingredient", availability: "Bengaluru produce", aliases: ["tamatar", "salad", "kachumber"], source: usdaSource },
  { id: "capsicum", name: "Green capsicum · raw", amount: 100, unit: "g", calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7, category: "Ingredient", availability: "Bengaluru produce", aliases: ["bell pepper", "shimla mirch"], source: usdaSource },
  { id: "onion", name: "Onion · raw", amount: 100, unit: "g", calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, category: "Ingredient", availability: "Bengaluru produce", aliases: ["pyaaz", "salad", "kachumber"], source: usdaSource },
  { id: "carrot", name: "Carrot · raw", amount: 100, unit: "g", calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8, category: "Ingredient", availability: "Bengaluru produce", aliases: ["gajar", "vegetable"], source: usdaSource },
  { id: "green-beans", name: "Green beans · raw", amount: 100, unit: "g", calories: 31, protein: 1.8, carbs: 7, fat: 0.2, fiber: 2.7, category: "Ingredient", availability: "Bengaluru produce", aliases: ["french beans", "beans", "vegetable"], source: usdaSource },
  { id: "bottle-gourd", name: "Bottle gourd · raw", amount: 100, unit: "g", calories: 14, protein: 0.6, carbs: 3.4, fat: 0.1, fiber: 0.5, category: "Ingredient", availability: "Bengaluru produce", aliases: ["lauki", "doodhi", "sorekaayi"], source: usdaSource },
  { id: "broccoli", name: "Broccoli · raw", amount: 100, unit: "g", calories: 34, protein: 2.8, carbs: 6.6, fat: 0.4, fiber: 2.6, category: "Ingredient", availability: "Bengaluru produce / quick commerce", aliases: ["broccoli", "vegetable"], source: usdaSource },
  { id: "pumpkin", name: "Pumpkin · raw", amount: 100, unit: "g", calories: 26, protein: 1, carbs: 6.5, fat: 0.1, fiber: 0.5, category: "Ingredient", availability: "Bengaluru produce", aliases: ["kaddu", "squash"], source: usdaSource },
  { id: "whole-egg", name: "Whole egg · reference", amount: 50, unit: "g", calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, fiber: 0, category: "Ingredient", availability: "Bengaluru staple", aliases: ["egg", "anda"], source: usdaSource },
  { id: "oil", name: "Cooking oil · reference", amount: 5, unit: "g", calories: 45, protein: 0, carbs: 0, fat: 5, fiber: 0, category: "Ingredient", availability: "Bengaluru staple", aliases: ["measured oil", "fat"], source: usdaSource },
  { id: "peanut-butter", name: "Peanut butter · smooth", amount: 32, unit: "g", calories: 188, protein: 8, carbs: 6, fat: 16, fiber: 1.9, category: "Ingredient", availability: "Widely available in India", aliases: ["groundnut butter", "spread"], source: usdaSource },
  { id: "almonds", name: "Almonds", amount: 28, unit: "g", calories: 164, protein: 6, carbs: 6.1, fat: 14.2, fiber: 3.5, category: "Ingredient", availability: "Bengaluru staple", aliases: ["badam", "nuts"], source: usdaSource },
  { id: "flax", name: "Flax seeds", amount: 20, unit: "g", calories: 107, protein: 3.7, carbs: 5.8, fat: 8.4, fiber: 5.5, category: "Ingredient", availability: "Online / supermarkets India", aliases: ["alsi", "seeds", "linseed"], source: usdaSource },
  { id: "sweet-potato", name: "Sweet potato · cooked", amount: 200, unit: "g", calories: 180, protein: 4, carbs: 41.4, fat: 0.3, fiber: 6.6, category: "Ingredient", availability: "Bengaluru produce", aliases: ["shakarkandi", "root vegetable"], source: usdaSource },
  { id: "brown-rice", name: "Brown rice · cooked", amount: 150, unit: "g", calories: 185, protein: 3.9, carbs: 38.4, fat: 1.6, fiber: 2.4, category: "Ingredient", availability: "Widely available in India", aliases: ["whole grain rice", "chawal"], source: usdaSource },
  { id: "greek-yogurt-nonfat", name: "Greek yogurt · non-fat reference", amount: 200, unit: "g", calories: 118, protein: 20.4, carbs: 7.2, fat: 0.8, fiber: 0, category: "Ingredient", availability: "Use exact local pack when available", aliases: ["strained yogurt", "hung curd", "dahi"], source: usdaSource },
];

type RecipeSeed = Omit<Food, "kind" | "brand" | "variant" | "category" | "calories" | "protein" | "carbs" | "fat" | "fiber" | "amount" | "unit" | "availability" | "aliases" | "source"> & {
  components: Food["components"];
  serving: string;
  brand?: string;
  aliases?: string[];
  source?: NutritionSource;
};

const recipeSeeds: RecipeSeed[] = [
  {
    id: "protein-brownies",
    name: "Fudgy banana protein brownies",
    serving: "¼ tray · about 3 squares",
    time: "35 min",
    totalMinutes: 35,
    tags: ["High protein", "Low fat", "Vegetarian", "Dessert"],
    art: "brownie",
    description: "Dark cocoa, banana and oats keep these properly fudgy; whey and Greek yogurt lift the protein without butter or refined flour.",
    ingredients: ["2 medium bananas · 236 g", "Rolled oats · 80 g", "Biozyme whey · 2 scoops / 66 g", "Unsweetened cocoa · 30 g", "Non-fat Greek yogurt · 200 g", "Egg whites · 100 g"],
    components: [{ foodId: "banana", amount: 59 }, { foodId: "oats", amount: 20 }, { foodId: "muscleblaze-biozyme-whey", amount: 0.5 }, { foodId: "cocoa", amount: 7.5 }, { foodId: "greek-yogurt-nonfat", amount: 50 }, { foodId: "egg-whites", amount: 25 }],
    method: ["Blend everything until smooth.", "Bake in a lined 20 cm tin at 175°C for 20–24 minutes.", "Cool fully; divide into four equal servings."],
    sourceNote: "Calculated as one quarter of the weighed recipe using USDA FoodData Central plus the current whey label. No added sugar or butter.",
  },
  {
    id: "chia-cardamom-bowl",
    name: "Cardamom chia protein bowl",
    serving: "1 breakfast bowl",
    time: "10 min + chill",
    totalMinutes: 130,
    tags: ["High protein", "High fibre", "Vegetarian", "No cook"],
    art: "chia",
    description: "Chia pudding meets Indian shrikhand notes: cardamom, thick yogurt, berries and half a scoop of whey.",
    ingredients: ["Chia seeds · 25 g", "Non-fat Greek yogurt · 200 g", "Nandini toned milk · 100 ml", "Strawberries · 100 g", "Biozyme whey · ½ scoop", "Cardamom + pinch of salt"],
    components: [{ foodId: "chia", amount: 25 }, { foodId: "greek-yogurt-nonfat", amount: 200 }, { foodId: "nandini-goodlife-toned", amount: 100 }, { foodId: "strawberries", amount: 100 }, { foodId: "muscleblaze-biozyme-whey", amount: 0.5 }],
    method: ["Whisk milk, yogurt, whey and cardamom.", "Stir in chia; chill at least 2 hours.", "Top with fruit immediately before eating."],
    sourceNote: "Ingredient-weight calculation from USDA reference foods and current product labels; fruit choice can shift totals slightly.",
  },
  {
    id: "cauli-chicken",
    name: "Pepper chicken cauliflower rice",
    serving: "1 large bowl",
    time: "30 min",
    totalMinutes: 30,
    tags: ["High protein", "Low fat", "High fibre", "Gluten free"],
    art: "cauli",
    description: "A genuinely filling cauliflower-rice bowl with pepper chicken, peas, beans, ginger and a bright lime finish.",
    ingredients: ["Cooked chicken breast · 150 g", "Cauliflower · 250 g", "Green peas · 50 g", "Green beans · 50 g", "Capsicum · 50 g", "Oil · 2 g", "Ginger, pepper, lime, coriander"],
    components: [{ foodId: "chicken-breast", amount: 150 }, { foodId: "cauliflower", amount: 250 }, { foodId: "green-peas-cooked", amount: 50 }, { foodId: "green-beans", amount: 50 }, { foodId: "capsicum", amount: 50 }, { foodId: "oil", amount: 2 }],
    method: ["Pulse cauliflower into rice-sized pieces.", "Sear spiced chicken in a non-stick pan; set aside.", "Stir-fry vegetables and cauliflower, then fold chicken through."],
    sourceNote: "Calculated from weighed USDA reference ingredients. The 2 g oil quantity is included, not treated as a free food.",
  },
  {
    id: "paneer-quinoa-tikka",
    name: "High-protein paneer tikka quinoa bowl",
    serving: "1 generous bowl",
    time: "35 min",
    totalMinutes: 35,
    tags: ["High protein", "Vegetarian"],
    art: "paneer",
    description: "Low-fat paneer, quinoa, charred vegetables and mint yogurt—tikka-shop satisfaction with every ingredient weighed.",
    ingredients: ["Amul High Protein Paneer · 150 g", "Cooked quinoa · 150 g", "Capsicum · 70 g", "Onion · 65 g", "Tomato · 65 g", "Non-fat mint yogurt · 100 g", "Tikka masala + lemon"],
    components: [{ foodId: "amul-high-protein-paneer", amount: 150 }, { foodId: "quinoa-cooked", amount: 150 }, { foodId: "capsicum", amount: 70 }, { foodId: "onion", amount: 65 }, { foodId: "tomato", amount: 65 }, { foodId: "greek-yogurt-nonfat", amount: 100 }],
    method: ["Marinate paneer and vegetables in half the yogurt and spices.", "Air-fry or grill until charred.", "Serve over quinoa with the remaining mint yogurt."],
    sourceNote: "Calculated from Amul’s official paneer label plus USDA reference ingredients.",
  },
  {
    id: "rajma-quinoa",
    name: "Rajma quinoa kachumber bowl",
    serving: "1 hearty bowl",
    time: "25 min with cooked beans",
    totalMinutes: 25,
    tags: ["Low fat", "High fibre", "Vegan", "Meal prep"],
    art: "rajma",
    description: "Rajma comfort with quinoa, a large kachumber and controlled oil; unusually high fibre without feeling worthy or austere.",
    ingredients: ["Cooked rajma · 150 g", "Cooked quinoa · 150 g", "Tomato · 50 g", "Cucumber · 50 g", "Onion · 50 g", "Oil · 5 g", "Rajma masala, lemon, coriander"],
    components: [{ foodId: "rajma-cooked", amount: 150 }, { foodId: "quinoa-cooked", amount: 150 }, { foodId: "tomato", amount: 50 }, { foodId: "cucumber", amount: 50 }, { foodId: "onion", amount: 50 }, { foodId: "oil", amount: 5 }],
    method: ["Warm rajma with masala and a splash of water.", "Season the chopped kachumber with lemon.", "Layer quinoa, rajma and salad; include the measured oil in cooking."],
    sourceNote: "Calculated from cooked USDA reference foods; bean variety and retained cooking liquid can shift totals.",
  },
  {
    id: "oats-egg-uttapam",
    name: "Oats egg-white uttapam plate",
    serving: "3 small uttapams + yogurt",
    time: "25 min",
    totalMinutes: 25,
    tags: ["High protein", "Low fat", "Breakfast"],
    art: "uttapam",
    description: "A crisp-edged oats batter packed with egg whites and vegetables, with cool yogurt instead of an oil-heavy chutney.",
    ingredients: ["Rolled oats · 40 g", "Egg whites · 200 g", "Onion · 50 g", "Tomato · 50 g", "Carrot · 50 g", "Non-fat Greek yogurt · 100 g", "Oil · 5 g", "Chilli, curry leaves, cumin"],
    components: [{ foodId: "oats", amount: 40 }, { foodId: "egg-whites", amount: 200 }, { foodId: "onion", amount: 50 }, { foodId: "tomato", amount: 50 }, { foodId: "carrot", amount: 50 }, { foodId: "greek-yogurt-nonfat", amount: 100 }, { foodId: "oil", amount: 5 }],
    method: ["Blend oats, egg whites and spices into a pourable batter.", "Fold in chopped vegetables.", "Cook three uttapams using all 5 g measured oil; serve with yogurt."],
    sourceNote: "Calculated from USDA reference ingredients. The full cooking-oil allowance is included.",
  },
  {
    id: "cocoa-banana-chia",
    name: "Chocolate banana chia pudding",
    serving: "1 dessert bowl",
    time: "10 min + chill",
    totalMinutes: 130,
    tags: ["High protein", "High fibre", "Vegetarian", "Dessert"],
    art: "cocoa",
    description: "The spoonable, deeply chocolate cousin of a protein shake—banana-sweetened and loaded with chia and cocoa fibre.",
    ingredients: ["Chia seeds · 25 g", "Non-fat Greek yogurt · 200 g", "Banana · 100 g", "Unsweetened cocoa · 10 g", "Biozyme whey · ½ scoop", "Water + pinch of salt"],
    components: [{ foodId: "chia", amount: 25 }, { foodId: "greek-yogurt-nonfat", amount: 200 }, { foodId: "banana", amount: 100 }, { foodId: "cocoa", amount: 10 }, { foodId: "muscleblaze-biozyme-whey", amount: 0.5 }],
    method: ["Blend banana, yogurt, whey, cocoa and water.", "Stir through chia.", "Chill for at least 2 hours; loosen with water if needed."],
    sourceNote: "Calculated from USDA reference ingredients and the current whey label.",
  },
  {
    id: "palak-paneer",
    name: "Lean palak paneer skillet",
    serving: "1 main bowl",
    time: "30 min",
    totalMinutes: 30,
    tags: ["High protein", "Vegetarian", "Gluten free"],
    art: "palak",
    description: "A spinach-heavy palak paneer using high-protein paneer and yogurt for body instead of cream.",
    ingredients: ["Amul High Protein Paneer · 150 g", "Spinach · 200 g", "Onion · 75 g", "Tomato · 75 g", "Non-fat Greek yogurt · 100 g", "Oil · 2 g", "Ginger, garlic, garam masala"],
    components: [{ foodId: "amul-high-protein-paneer", amount: 150 }, { foodId: "spinach", amount: 200 }, { foodId: "onion", amount: 75 }, { foodId: "tomato", amount: 75 }, { foodId: "greek-yogurt-nonfat", amount: 100 }, { foodId: "oil", amount: 2 }],
    method: ["Wilt and blend spinach with ginger and chilli.", "Cook onion-tomato masala in measured oil.", "Fold in spinach, yogurt and paneer; warm gently."],
    sourceNote: "Calculated from Amul’s official paneer label plus USDA reference ingredients. Yogurt replaces cream.",
  },
  {
    id: "tandoori-quinoa",
    name: "Tandoori chicken quinoa kachumber",
    serving: "1 dinner plate",
    time: "40 min",
    totalMinutes: 40,
    tags: ["High protein", "Low fat", "Meal prep"],
    art: "tandoori",
    description: "Charred yogurt-marinated chicken, quinoa and a mountain of kachumber—big dinner energy with a lean macro shape.",
    ingredients: ["Cooked chicken breast · 150 g", "Cooked quinoa · 150 g", "Cucumber · 70 g", "Tomato · 65 g", "Onion · 65 g", "Non-fat Greek yogurt · 100 g", "Tandoori spices, lemon, coriander"],
    components: [{ foodId: "chicken-breast", amount: 150 }, { foodId: "quinoa-cooked", amount: 150 }, { foodId: "cucumber", amount: 70 }, { foodId: "tomato", amount: 65 }, { foodId: "onion", amount: 65 }, { foodId: "greek-yogurt-nonfat", amount: 100 }],
    method: ["Marinate chicken in yogurt, lemon and spices.", "Grill or air-fry until cooked and lightly charred.", "Plate with quinoa and a large chopped kachumber."],
    sourceNote: "Calculated from USDA reference ingredients; no invisible oil is assumed.",
  },
  {
    id: "greek-yogurt-chaat",
    name: "Crunchy Greek-yogurt chana chaat",
    serving: "1 lunch bowl",
    time: "15 min",
    totalMinutes: 15,
    tags: ["High protein", "High fibre", "Vegetarian", "No cook"],
    art: "chaat",
    description: "Creamy, tangy chaat built around yogurt and chickpeas, with chia for crunch and no fried sev hiding in the arithmetic.",
    ingredients: ["Natural Greek yogurt · 270 g", "Cooked chickpeas · 100 g", "Cucumber · 50 g", "Tomato · 50 g", "Onion · 50 g", "Chia seeds · 10 g", "Chaat masala, mint, lemon"],
    components: [{ foodId: "epigamia-natural-greek", amount: 270 }, { foodId: "chickpeas-cooked", amount: 100 }, { foodId: "cucumber", amount: 50 }, { foodId: "tomato", amount: 50 }, { foodId: "onion", amount: 50 }, { foodId: "chia", amount: 10 }],
    method: ["Season yogurt with mint and chaat masala.", "Fold through chickpeas and chopped vegetables.", "Finish with chia, lemon and coriander."],
    sourceNote: "Calculated from product-label yogurt and USDA reference ingredients; recheck the exact yogurt pack before production use.",
  },
];

/** "Brand · Name · Variant" is the display identity; seeds may fold the variant into the name with " · ". */
function splitIdentity(food: { name: string; brand?: string; variant?: string }) {
  const [name, ...variantParts] = food.name.split(" · ");
  return {
    brand: food.brand?.trim() || "Generic",
    name: name.trim(),
    variant: food.variant?.trim() || variantParts.join(" · ").trim(),
  };
}

const seedProductFoods: Food[] = productSeeds.map((food) => ({
  ...food,
  ...splitIdentity(food),
  kind: "product" as const,
  category: food.category ?? "Product",
}));

const seedRecipeFoods: Food[] = recipeSeeds.map((recipe) => ({
  ...recipe,
  ...splitIdentity({ name: recipe.name, brand: recipe.brand ?? "Nourish kitchen" }),
  kind: "recipe" as const,
  category: "Meal" as const,
  // One recipe record is one serving; components are weighed per serving.
  amount: 1,
  unit: "serving" as const,
  availability: recipe.serving,
  aliases: recipe.aliases ?? recipe.tags ?? [],
  source: recipe.source ?? { label: "Calculated from weighed ingredients", url: SOURCE_LINKS.ifct, trust: "Reference" },
  ...{ calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 },
}));

/** The single catalogue. Recipe macros are filled in here from their components. */
export const seedCatalog: Food[] = resolveCatalog([...seedProductFoods, ...seedRecipeFoods]);

/** Derived views over the one catalogue — filters, not parallel data. */
export const seedProducts = seedCatalog.filter((food) => food.kind === "product");
export const seedRecipes = seedCatalog.filter((food) => food.kind === "recipe");
